development:
  adapter: postgresql
  database: adman_development
  host: localhost
  # user: blisaur
  user: kevin
  password: 

test:
  adapter: postgresql
  database: adman_test
  host: localhost
  # user: blisaur
  user: kevin
  password: 
